### ISSUE TITLE
got fatal error 

### ISSUE THREAD

**Issue by albertusputra** [ajfranzoia/cakephp-mailgun#1]
Fatal error: Class 'Mailgun\Mailgun' not found in /home/k4741812/public_html/Plugin/Mailgun/Lib/Network/Email/MailgunTransport.php on line 80

do I need to put the mailgun php library? http://documentation.mailgun.com/libraries.html#php

where do I need to put it?

because at your plugin line 12, has this use Mailgun\Mailgun;

**Comment by ajfranzoia** [comment]
Yes, Mailgun SDK is required. I've updated readme with better instructions. You will have to install it via Composer (and php 5.4+), so Mailgun gets installed and loaded automatically. 
Otherwise, in order to make it work, you will have to install Mailgun by yourself, edit the transport file, remove the `use Mailgun\Mailgun` statement and load Mailgun before sending any email.

Let me know if you have any other issues.

**Comment by anupalhub** [comment]
I removed the line <code>use Mailgun\Mailgun</code> 
Now i get the error <code>Class 'Mailgun' not found </code>

**Comment by andrebruton** [comment]
I have the same error on a shared server. I can not use composer and it looks like all the development I've done to change from Mandrill to Mailgun is useless. I wish Mailgun had a standalone source files that just worked.

**Comment by ajfranzoia** [comment]
@anupalusoft 
`Class 'Mailgun' not found` means the Mailgun sources aren't being included before the file. Did you check if they were required properly?

@andrebruton 
For shared host installations they have given some instructions here which might work: https://github.com/mailgun/mailgun-php/blob/master/SharedHostInstall.md.
